kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - ./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/zulu8 clean build publish --no-daemon
  environment:
    GPR_USERNAME:
      from_secret: gpr_username
    GPR_TOKEN:
      from_secret: gpr_token
